### ISSUE TITLE
Using it with for v7.2

### ISSUE THREAD

**Issue by levraipixel** [Aamir010/jahia-docker#1]
Hi,

I'am trying to use this with v7.2.0.1-r55404, and the automated installation fails due to missing data in the auto-install.xml -> How did you generate yours? How can I generate my own?
Thanks and have a nice day

**Comment by Aamir010** [comment]
Take a pull now. I have updated a code with a latest version

**Comment by levraipixel** [comment]
Wow thanks, it works like a charm. I'm working on a few tiny improvements, I'll try to propose a pull request soon.

**Comment by levraipixel** [comment]
See #2
